name: whatsapp_story_editor
description: A Flutter package to add story editing features similar to Whatsapp.
version: 0.0.5
homepage: https://github.com/JaveriaJR/whatsapp_story_editor/tree/main


environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  whatsapp_camera: ^1.0.0
  photofilters: ^3.0.1
  perfect_freehand: ^1.0.4
  image_crop_plus_updated: ^0.7.1
  hsv_color_pickers: ^0.2.2 
  get: ^4.6.1
  path_provider: ^2.0.12 
  flutter_svg: ^2.0.4

  dotted_border: ^2.0.0+2
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  # matrix_gesture_detector: 
  #   git:
  #     url: https://github.com/JaveriaJR/matrix_gesture_detector.git
  #     ref: master 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/icons/story.png
    - assets/icons/send.png
    - assets/stickers/
    - assets/stickers/2/
    - assets/emojies/
    # - packages/whatsapp_story_editor/assets/stickers/
    # - packages/whatsapp_story_editor/assets/stickers/2/ 
    # - packages/whatsapp_story_editor/assets/icons/story.png

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
